= Модификация списка товаров

== Документация API

=== Доработка избранного

Для работы избранного нам потребуется:

* Добавить новый POST-метод для добавления товара и DELETE-метод для удаления из списка избранного

* Для отображения продукта как избранного в общем потоке в ответ в списке продуктов необходимо добавить булево поле `isFavourite`.

* Для просмотра списка своих избранных так же следует добавить путь `/favourite`, возвращающий их список. За основу следует взять результат от `/products`, чтобы сохранить работу фильтров

* Для доступа только зарегистрированным пользователям делать проверку по JWT-токену для этих путей

=== Доработка изображений

Для возможности иметь несколько изображений для товара, сохраняя обратную совместимость,
все дополнительные изображения стоит возвращать в отдельном поле `images`, представляющее из себя массив строк со ссылками на изображения.

== Реализация

В первую очередь, нам необходимо уйти от прямой работы с файловой системой через FileStorageRepository.
Вместо этого нам следует создать универсальный интерфейс плагина, который будут поддерживать схожий с репозиторием интерфейс.
В нашем случае их будет два: `LocalStoragePlugin` и `S3Plugin`, причем первый - это уже имеющийся FileStorageRepository (они не представлены в репозитории, поскольку банально содержат логику работы с хранилищем). Таким образом, наш `Product`
продолжит работать без изменений, а мы сможем в дальнейшем расширять через плагины систему хранения файлов.

NOTE: Product.php содержит поле с именем файла, но оно приватное и нигде нет способа его заполнить. Выглядит забавно :)

Дальнейшие доработки связаны лишь с вызовом репозитория не единожды для одного файла, а для их серии.

== Тестирование

Тестирование следует организовать следующим образом:

. Юнит-тестирование, где целью будет проверить корректность работы нашего модуля
(для этого представим, что Product является фасадом нашего модуля). При этом все внешние зависимости
будут замоканы. Для этого подойдёт PHPUnit. 
. Тестирование нашего API, дабы убедиться, что вся наша система взаимодействует корректно. Это можно сделать с помошью
Codeception, либо любой другой системы
. Чтобы убедиться, что наши тесты действительно работают,
можно добавить мутационное тестирование. 
