= Docker: Модификация конфигурации сервисов docker-compose

== Текст задания

Есть конфигурация сервисов docker-compose.yml, требующая модификации. Необходимо:
* добавить в этот файл сервис где будет работать приложение php
* переопределить сервис базы данных на mysql 8 не меняя текущий файл
* объединить все сервисы в одну сеть
* настройки портов и конфигурация сервиса nginx default.conf должны изменяться извне

[source,yaml]
----
version: '3'
    services:
        nginx:
            image: nginx:alpine
            container_name: app-nginx
            ports:
                - "8090:8090"
                - "443:443"
            volumes:
                - ./:/var/www
        db:
            platform: linux/x86_64
            image: mysql:5.6.47
            container_name: app-db
            ports:
                - "3306:3306"
            volumes:
                - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
                - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql
----

== Описание решения

* Описание сервиса для приложения на php

[source,yaml]
----
....
app:
    image: php:8-fpm
    volumes:
        - ./:/var/www
....
----

* Чтобы переопределить сервис базы данных без смены файла, необходимо создать новый файл, к примеру
`docker-compose-mysql8.yaml`, описать в нём наш сервис базы данных с таким же именем, но иными
параметрами и запустить, явно указав порядок конфигурационных файлов

[source, bash]
----
$ docker compose -f docker-compose.yaml -f docker-compose-mysql8.yaml up
----

* По умолчанию docker compose уже создаёт стандартную сеть для наших приложений. Однако мы можем
указать явно параметры данной сети:

[source,yaml]
----
....
network:
    appnetwork:
        driver: weave
....
----

* Чтобы иметь возможность конфигурировать nginx извне (через переменные среды), необходимо
подготовить директорию с шаблонами конфигурации, которые мы хотели бы изменять (порт, хост и т.д.),
подключить её как volume и указать нужные переменные среды. Итоговый результат nginx разместит
в `/etc/nginx/conf.d`