= Composer: Обновление зависимости

== Текст задания
У вас есть проект, который использует библиотеку. Вам необходимо:

* внести изменения в библиотеку и протестировать ее работоспособность в проекте
* после успешного прохождения тестов вам необходимо выпустить релиз проекта с измененной библиотекой

Опишите Ваши действия в git и composer на всех этапах
(разработка, тестирование, релиз и деплой).

== Описание решения

. Внести свои изменения и протестировать их (вручную, либо же phpunit)
. В `composer.json` библиотеки обновить версию библиотеки:
.. В случае незначительных изменений без поломки обратной совместимости рекомендуется поднять версию
PATCH (1.1.15 -> 1.1.16)
.. При значительной доработке без поломки обратной совместимости (например, добавление новой
функциональности) -- поднять версию MINOR (1.1.15 -> 1.2.0)
.. При поломке обратной совместимости -- поднять MAGOR (1.1.15 -> 2.0.0)
. Запушить изменения в Github/Gitlab, дождаться успешного прохождения CI, получить апрув от команды
Так же важным будет выставить тэг, соответствующий версии приложения, дабы CI отработал корректно
. После вмёрживания изменений внести правки в проектах, использующие нашу библиотеку. Для этого
в composer.json проекта необходимо внести обновлённую версию и выполнить `composer update --lock`
